### ISSUE TITLE
Add Google Tag Manager and Google Analytics

### ISSUE THREAD

**Issue by uxder** [blinkk/amagaki-plugin-page-builder#29]
I believe adding google tag manager and analytics requires adding it via `extra` at the moment.

Example:
```
    head: {
      extra: ['/views/head.njk'],
    },
```

Since it is very common for a site to use tag manager and analytics, I think it could be a build in PageBuilderOption.

If this sounds good, I'm happy to make a PR for it.

**Comment by jeremydw** [comment]
It is definitely common for a site to use GTM and Google Analytics, but I'm not sure we should build it in to the head options. Why? The snippets keep changing depending on the version of GTM/GA used. Additionally, when using GA or similar tools, sometimes we need to set `dataLayer` or make other configurations prior to loading GA/GTM.

I'm open to the discussion more if we think there's a good way we can solve for this, but I've seen too much variation in snippets used to feel confident about making built-in support for it.

That said, if our built-in support supported all the different ways to use snippets, I'm all for it...

NOTE: GTM has less variance than Google Analytics. As far as I know there's only one GTM snippet (versus GA which had `analytics.js` `ga.js` GA4 and other snippets. GA4 is also backwards incompatible with previous snippets. So, we could add support for GTM? What happens when GTM changes their snippet?

https://developers.google.com/tag-platform/tag-manager/web#custom_web_installations

**Comment by uxder** [comment]
Okay that makes sense :)
